Develop
KokosSPb/SPBSTU_microservice pull request #1
Opened 2024-04-29 20:11 UTC by KokosSPb

2024-04-29 20:14 UTC, vladefr97 requested changes

2024-04-29 20:14 UTC, vladefr97 commented on task1/1 - palindrome/1 - palindrome.ipynb
> +{
Залей питоновские файлы (с расширением .py), а не юпитер ноутбки

2024-04-29 20:36 UTC, KokosSPb commented on task1/1 - palindrome/1 - palindrome.ipynb
> +{
Вы же разрешили делать в Jupiter Notebook =)

2024-04-29 21:04 UTC, vladefr97 approved these changes

2024-04-29 21:04 UTC, vladefr97 commented on task1/3 - shapes/shapes.py
> +class Shapes:
Классы называем в единственном числе

2024-04-29 21:05 UTC, KokosSPb commented on task1/3 - shapes/shapes.py
> +class Shapes:
Почему? Это не логично. Логично экземпляры классов называть в единственном, а сами классы во множественном

2024-05-24 09:56 UTC, merged

2024-05-24 10:40 UTC, vladefr97 commented on task2/config.php
> +	$pass = "vertrigo";
Секретную информацию нельзя заливать в репозиторий

2024-05-24 10:40 UTC, vladefr97 commented on task2/config.php
> +	$pass = "vertrigo";
Нужно использовать .env файл, репозиторий заливается только .env.example

2024-05-24 10:40 UTC, vladefr97 commented on task2/config.php
> +<?php
Надо разделить код на несколько файлов

2024-05-24 10:40 UTC, vladefr97 commented on task2/functions.php
> +	$STH = $DBH->prepare("INSERT INTO `students` (`id`, `name`, `fname`, `lname`, `gr`) VALUES (NULL, '".$data['name']."', '".$data['fname']."', '".$data['lname']."', '".$data['gr']."');");
Нельзя использовать сырой sql в коде. Нужно использовать модель данных бд в коде (ORM)

2024-05-24 10:40 UTC, vladefr97 commented on task2/functions.php
> +		http_response_code(404);
не хардкодь http статусы в коде. Нужно использовать перечисления (enum).

2024-05-24 10:40 UTC, vladefr97 commented on task2/functions.php
> +{
В коде нет разделения слоев api, работы с бд, бизнес логики приложения